version: '3.8'

services:
  api:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    ports:
      - "5050:80"
      - "5051:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=notkrisp;Username=postgres;Password=postgres
    depends_on:
      - db
    volumes:
      - ./app/backend:/src
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
      - ~/.aspnet/https:/root/.aspnet/https:ro

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=notkrisp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 