services:
  - type: web
    name: not-krisp-backend-prod
    env: docker
    dockerfilePath: app/backend/Dockerfile
    plan: starter
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres-db
          property: connectionString

  - type: web
    name: not-krisp-frontend-prod
    env: docker
    dockerfilePath: app/frontend/Dockerfile
    plan: starter
    envVars:
      - key: VITE_API_URL
        value: https://not-krisp-backend-prod.onrender.com

  - type: web
    name: not-krisp-backend-staging
    env: docker
    dockerfilePath: app/backend/Dockerfile
    plan: starter
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Staging
      - key: ASPNETCORE_URLS
        value: http://+:5000
      - key: DATABASE_URL
        fromDatabase:
          name: postgres-db
          property: connectionString
    healthCheckPath: /health
    branch: staging

  - type: web
    name: not-krisp-frontend-staging
    env: docker
    dockerfilePath: app/frontend/Dockerfile
    plan: starter
    envVars:
      - key: NODE_ENV
        value: staging
      - key: VITE_API_URL
        value: https://not-krisp-backend-staging.onrender.com
    healthCheckPath: /
    branch: staging

databases:
  - name: postgres-db
    databaseName: notkrisp
    user: notkrisp
    plan: starter
