FROM mcr.microsoft.com/dotnet/sdk:9.0-preview

WORKDIR /app

COPY . .
RUN dotnet restore

ENV ASPNETCORE_URLS=http://+:5149
ENV DOTNET_USE_POLLING_FILE_WATCHER=1

EXPOSE 5149

ENTRYPOINT ["dotnet", "watch", "run", "--project", "NotKrisp.Core.csproj"] 